name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: packages/portfolio2024
        run: pnpm install

      - name: Build project
        working-directory: packages/portfolio2024
        run: pnpm run build

      - name: Add SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H dlfly.seoul.kr >> ~/.ssh/known_hosts

      - name: Create target directory on server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa username@server_ip "mkdir -p /path/to/deploy"

      - name: Deploy to Server
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" packages/portfolio2024/dist/ username@server_ip:/path/to/deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      # - name: Deploy to Server
      #   run: |
      #     rsync -avz --delete packages/portfolio2024/ dlfly@dlfly.seoul.kr:/path/to/deploy/portfolio2024
      #   run: |
      #     rsync -avz --delete packages/portfolio2024/dist/ dlfly@dlfly.seoul.kr:/path/to/deploy
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
